/**
 * Acciones sobre tareas que deben registrarse en la auditoría.
 */
export enum AccionAuditoria {
  CREAR_TAREA = 'CREAR_TAREA',
  ACTUALIZAR_TAREA = 'ACTUALIZAR_TAREA',
  CAMBIAR_ESTADO_TAREA = 'CAMBIAR_ESTADO_TAREA',
  ACTUALIZAR_ETIQUETAS_TAREA = 'ACTUALIZAR_ETIQUETAS_TAREA',
  ASIGNAR_USUARIO_TAREA = 'ASIGNAR_USUARIO_TAREA',
  ELIMINAR_TAREA = 'ELIMINAR_TAREA',
}
